// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MknMs.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MknMs.Infrastructure.Migrations
{
    [DbContext(typeof(MknDbContext))]
    [Migration("20261010151044_AddAttendanceRuleAndAgAmendmentEntities")]
    partial class AddAttendanceRuleAndAgAmendmentEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MknMs.Domain.D10_ConfigLookups.AssignmentStatus", b =>
                {
                    b.Property<int>("AssignmentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignment_status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignmentStatusId"));

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_terminal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("AssignmentStatusId")
                        .HasName("pk_assignment_status");

                    b.ToTable("assignment_status");
                });

            modelBuilder.Entity("MknMs.Domain.D10_ConfigLookups.Capability", b =>
                {
                    b.Property<int>("CapabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("capability_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CapabilityId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("CapabilityId")
                        .HasName("pk_capability");

                    b.ToTable("capability");
                });

            modelBuilder.Entity("MknMs.Domain.D10_ConfigLookups.OutcomeState", b =>
                {
                    b.Property<int>("OutcomeStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("outcome_state_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OutcomeStateId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("OutcomeStateId")
                        .HasName("pk_outcome_state");

                    b.ToTable("outcome_state");
                });

            modelBuilder.Entity("MknMs.Domain.D10_ConfigLookups.PermissionTier", b =>
                {
                    b.Property<int>("PermissionTierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("permission_tier_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionTierId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("PermissionTierId")
                        .HasName("pk_permission_tier");

                    b.ToTable("permission_tier");
                });

            modelBuilder.Entity("MknMs.Domain.D10_ConfigLookups.ServiceType", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("service_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("ServiceTypeId")
                        .HasName("pk_service_type");

                    b.ToTable("service_type");
                });

            modelBuilder.Entity("MknMs.Domain.D10_ConfigLookups.TimeOfDay", b =>
                {
                    b.Property<int>("TimeOfDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("time_of_day_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TimeOfDayId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("TimeOfDayId")
                        .HasName("pk_time_of_day");

                    b.ToTable("time_of_day");
                });

            modelBuilder.Entity("MknMs.Domain.D11_SystemSetting.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("system_setting");
                });

            modelBuilder.Entity("MknMs.Domain.D12_MaterializerRun.MaterializerRun", b =>
                {
                    b.Property<int>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RunId"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text")
                        .HasColumnName("error_detail");

                    b.Property<int>("OccurrencesCreated")
                        .HasColumnType("integer")
                        .HasColumnName("occurrences_created");

                    b.Property<int>("SchedulesEvaluated")
                        .HasColumnType("integer")
                        .HasColumnName("schedules_evaluated");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger_type");

                    b.Property<int?>("TriggeredBy")
                        .HasColumnType("integer")
                        .HasColumnName("triggered_by");

                    b.HasKey("RunId");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_materializer_run_started_at");

                    b.HasIndex("TriggeredBy");

                    b.ToTable("materializer_run", t =>
                        {
                            t.HasCheckConstraint("chk_materializer_run_status", "(status = 'Success' AND completed_at IS NOT NULL) OR (status = 'Failure' AND error_detail IS NOT NULL)");

                            t.HasCheckConstraint("chk_materializer_run_status_value", "status IN ('Success', 'Failure')");

                            t.HasCheckConstraint("chk_materializer_run_trigger", "(trigger_type = 'Manual' AND triggered_by IS NOT NULL) OR (trigger_type = 'Scheduled' AND triggered_by IS NULL)");

                            t.HasCheckConstraint("chk_materializer_run_trigger_type", "trigger_type IN ('Scheduled', 'Manual')");
                        });
                });

            modelBuilder.Entity("MknMs.Domain.D13_AttendanceRule.AttendanceRule", b =>
                {
                    b.Property<int>("AttendanceRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attendance_rule_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttendanceRuleId"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("OutcomeStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("outcome_status_id");

                    b.Property<string>("OutcomeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outcome_type");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger_type");

                    b.Property<string>("TriggerValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trigger_value");

                    b.HasKey("AttendanceRuleId")
                        .HasName("pk_attendance_rule");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("ix_attendance_rule_enabled");

                    b.HasIndex("OutcomeStatusId")
                        .HasDatabaseName("ix_attendance_rule_outcome_status_id");

                    b.ToTable("attendance_rule");
                });

            modelBuilder.Entity("MknMs.Domain.D13_AttendanceRule.AttendanceRuleScope", b =>
                {
                    b.Property<int>("AttendanceRuleId")
                        .HasColumnType("integer")
                        .HasColumnName("attendance_rule_id");

                    b.Property<string>("CriteriaType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criteria_type");

                    b.Property<string>("CriteriaValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("criteria_value");

                    b.HasKey("AttendanceRuleId", "CriteriaType", "CriteriaValue");

                    b.ToTable("attendance_rule_scope");
                });

            modelBuilder.Entity("MknMs.Domain.D13_AttendanceRule.Readmission", b =>
                {
                    b.Property<int>("ReadmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("readmission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReadmissionId"));

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("PerformedByAdminId")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by_admin_id");

                    b.Property<DateOnly>("ReadmissionDate")
                        .HasColumnType("date")
                        .HasColumnName("readmission_date");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("ReadmissionId")
                        .HasName("pk_readmission");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_readmission_member");

                    b.HasIndex("PerformedByAdminId")
                        .HasDatabaseName("ix_readmission_performed_by_admin_id");

                    b.ToTable("readmission");
                });

            modelBuilder.Entity("MknMs.Domain.D14_ConfigurationAudit.ConfigurationAuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int>("ApprovedByAdminId")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by_admin_id");

                    b.Property<string>("ConsequencesOccurred")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consequences_occurred");

                    b.Property<string>("ConsequencesPreviewed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consequences_previewed");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_name");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<int>("InitiatedByAdminId")
                        .HasColumnType("integer")
                        .HasColumnName("initiated_by_admin_id");

                    b.Property<DateTimeOffset?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notified_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.HasKey("AuditId");

                    b.HasIndex("ApprovedByAdminId")
                        .HasDatabaseName("ix_configuration_audit_log_approved_by_admin_id");

                    b.HasIndex("InitiatedByAdminId")
                        .HasDatabaseName("ix_configuration_audit_log_initiated_by_admin_id");

                    b.HasIndex("NotifiedAt")
                        .HasDatabaseName("ix_configuration_audit_log_notified_at");

                    b.ToTable("configuration_audit_log");
                });

            modelBuilder.Entity("MknMs.Domain.D14_ConfigurationAudit.EntityDeletionPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("policy_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PolicyId"));

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("RequiredDeactivatePermissionTierId")
                        .HasColumnType("integer")
                        .HasColumnName("required_deactivate_permission_tier_id");

                    b.Property<int?>("RequiredDeletePermissionTierId")
                        .HasColumnType("integer")
                        .HasColumnName("required_delete_permission_tier_id");

                    b.Property<bool>("RequiresApprovalForDeactivate")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_approval_for_deactivate");

                    b.Property<bool>("RequiresApprovalForDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_approval_for_delete");

                    b.Property<bool>("RequiresReasonForDeactivate")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_reason_for_deactivate");

                    b.Property<bool>("RequiresReasonForDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_reason_for_delete");

                    b.HasKey("PolicyId");

                    b.HasIndex("EntityType")
                        .IsUnique()
                        .HasDatabaseName("uq_entity_deletion_policy_entity_type");

                    b.HasIndex("RequiredDeactivatePermissionTierId")
                        .HasDatabaseName("ix_entity_deletion_policy_required_deactivate_permission_tier_~");

                    b.HasIndex("RequiredDeletePermissionTierId")
                        .HasDatabaseName("ix_entity_deletion_policy_required_delete_permission_tier_id");

                    b.ToTable("entity_deletion_policy");
                });

            modelBuilder.Entity("MknMs.Domain.D14_ConfigurationAudit.NotificationSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("RecipientAdminId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_admin_id");

                    b.Property<int?>("RecipientTierId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_tier_id");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("RecipientAdminId")
                        .HasDatabaseName("ix_notification_subscription_recipient_admin_id");

                    b.HasIndex("RecipientTierId")
                        .HasDatabaseName("ix_notification_subscription_recipient_tier_id");

                    b.ToTable("notification_subscription", t =>
                        {
                            t.HasCheckConstraint("chk_notification_subscription_recipient", "(recipient_tier_id IS NOT NULL AND recipient_admin_id IS NULL) OR (recipient_tier_id IS NULL AND recipient_admin_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MknMs.Domain.D1_RoleDuty.Duty", b =>
                {
                    b.Property<int>("DutyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("duty_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DutyId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("DutyId")
                        .HasName("pk_duty");

                    b.ToTable("duty");
                });

            modelBuilder.Entity("MknMs.Domain.D1_RoleDuty.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("RoleId")
                        .HasName("pk_role");

                    b.ToTable("role");
                });

            modelBuilder.Entity("MknMs.Domain.D2_DutyRule.DutyRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rule_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RuleId"));

                    b.Property<string>("CriteriaType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criteria_type");

                    b.Property<string>("CriteriaValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("criteria_value");

                    b.Property<int>("DutyId")
                        .HasColumnType("integer")
                        .HasColumnName("duty_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("TierOrder")
                        .HasColumnType("integer")
                        .HasColumnName("tier_order");

                    b.HasKey("RuleId");

                    b.HasIndex("DutyId", "TierOrder")
                        .HasDatabaseName("ix_duty_rule_duty_tier");

                    b.ToTable("duty_rule");
                });

            modelBuilder.Entity("MknMs.Domain.D3_BranchTimeSlotService.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BranchId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("BranchId")
                        .HasName("pk_branch");

                    b.ToTable("branch");
                });

            modelBuilder.Entity("MknMs.Domain.D3_BranchTimeSlotService.BranchTimeSlot", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("time_slot_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TimeSlotId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("TimeOfDayId")
                        .HasColumnType("integer")
                        .HasColumnName("time_of_day_id");

                    b.HasKey("TimeSlotId");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_branch_time_slot_branch");

                    b.HasIndex("TimeOfDayId")
                        .HasDatabaseName("ix_branch_time_slot_time_of_day_id");

                    b.ToTable("branch_time_slot");
                });

            modelBuilder.Entity("MknMs.Domain.D3_BranchTimeSlotService.ServiceDefinition", b =>
                {
                    b.Property<int>("ServiceDefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("service_def_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceDefId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("OwningBranchId")
                        .HasColumnType("integer")
                        .HasColumnName("owning_branch_id");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("service_type_id");

                    b.HasKey("ServiceDefId");

                    b.HasIndex("OwningBranchId")
                        .HasDatabaseName("ix_service_definition_owning_branch");

                    b.HasIndex("ServiceTypeId")
                        .HasDatabaseName("ix_service_definition_service_type");

                    b.ToTable("service_definition");
                });

            modelBuilder.Entity("MknMs.Domain.D3_BranchTimeSlotService.ServiceDefinitionDuty", b =>
                {
                    b.Property<int>("ServiceDefId")
                        .HasColumnType("integer")
                        .HasColumnName("service_def_id");

                    b.Property<int>("DutyId")
                        .HasColumnType("integer")
                        .HasColumnName("duty_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("RequiredSlotCount")
                        .HasColumnType("integer")
                        .HasColumnName("required_slot_count");

                    b.HasKey("ServiceDefId", "DutyId");

                    b.HasIndex("DutyId")
                        .HasDatabaseName("ix_service_definition_duty_duty");

                    b.ToTable("service_definition_duty");
                });

            modelBuilder.Entity("MknMs.Domain.D3_BranchTimeSlotService.ServiceOccurrence", b =>
                {
                    b.Property<int>("OccurrenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OccurrenceId"));

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<int?>("FillStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("fill_status_id");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("generated_by");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.Property<int?>("ServiceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("service_type_id");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("OccurrenceId");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_service_occurrence_date");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_service_occurrence_event_id");

                    b.HasIndex("FillStatusId")
                        .HasDatabaseName("ix_service_occurrence_fill_status_id");

                    b.HasIndex("ServiceTypeId")
                        .HasDatabaseName("ix_service_occurrence_service_type_id");

                    b.HasIndex("ScheduleId", "Date")
                        .IsUnique()
                        .HasDatabaseName("uq_service_occurrence_schedule_date")
                        .HasFilter("schedule_id IS NOT NULL");

                    b.ToTable("service_occurrence", t =>
                        {
                            t.HasCheckConstraint("chk_service_occurrence_generated_by", "generated_by IN ('System', 'Administrator')");

                            t.HasCheckConstraint("chk_service_occurrence_provenance", "(generated_by = 'System' AND created_by IS NULL) OR (generated_by = 'Administrator' AND created_by IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MknMs.Domain.D3_BranchTimeSlotService.ServiceOccurrenceDuty", b =>
                {
                    b.Property<int>("OccurrenceId")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_id");

                    b.Property<int>("DutyId")
                        .HasColumnType("integer")
                        .HasColumnName("duty_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<int?>("RequiredSlotCount")
                        .HasColumnType("integer")
                        .HasColumnName("required_slot_count");

                    b.HasKey("OccurrenceId", "DutyId");

                    b.HasIndex("DutyId")
                        .HasDatabaseName("ix_service_occurrence_duty_duty");

                    b.ToTable("service_occurrence_duty", t =>
                        {
                            t.HasCheckConstraint("chk_service_occurrence_duty_action", "action IN ('Added', 'Removed')");
                        });
                });

            modelBuilder.Entity("MknMs.Domain.D3_BranchTimeSlotService.ServiceSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("ServiceDefId")
                        .HasColumnType("integer")
                        .HasColumnName("service_def_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("integer")
                        .HasColumnName("time_slot_id");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ServiceDefId")
                        .HasDatabaseName("ix_service_schedule_service_def");

                    b.HasIndex("TimeSlotId")
                        .HasDatabaseName("ix_service_schedule_time_slot");

                    b.HasIndex("ServiceDefId", "TimeSlotId")
                        .IsUnique()
                        .HasDatabaseName("uq_service_schedule_active")
                        .HasFilter("is_active = TRUE");

                    b.ToTable("service_schedule");
                });

            modelBuilder.Entity("MknMs.Domain.D4_Member.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("admin_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminId"));

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("PermissionTierId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_tier_id");

                    b.HasKey("AdminId")
                        .HasName("pk_admin");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_admin_member");

                    b.HasIndex("PermissionTierId")
                        .HasDatabaseName("ix_admin_tier");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("MknMs.Domain.D4_Member.AttributeType", b =>
                {
                    b.Property<int>("AttributeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attribute_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttributeTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("AttributeTypeId")
                        .HasName("pk_attribute_type");

                    b.ToTable("attribute_type");
                });

            modelBuilder.Entity("MknMs.Domain.D4_Member.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("date")
                        .HasColumnName("join_date");

                    b.Property<string>("MembershipStage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("membership_stage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("surname");

                    b.HasKey("MemberId")
                        .HasName("pk_member");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_member_branch");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_member_role");

                    b.ToTable("member");
                });

            modelBuilder.Entity("MknMs.Domain.D4_Member.MemberAttributeValue", b =>
                {
                    b.Property<int>("MemberAttributeValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("member_attribute_value_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberAttributeValueId"));

                    b.Property<int>("AttributeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("attribute_type_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("integer")
                        .HasColumnName("recorded_by");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date")
                        .HasColumnName("recorded_date");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("MemberAttributeValueId")
                        .HasName("pk_member_attribute_value");

                    b.HasIndex("AttributeTypeId")
                        .HasDatabaseName("ix_member_attribute_value_attribute_type_id");

                    b.HasIndex("RecordedBy");

                    b.HasIndex("MemberId", "AttributeTypeId")
                        .IsUnique()
                        .HasDatabaseName("uq_member_attribute_value_member_type");

                    b.ToTable("member_attribute_value");
                });

            modelBuilder.Entity("MknMs.Domain.D4_Member.MemberStatus", b =>
                {
                    b.Property<int>("MemberStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("member_status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberStatusId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRosterable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rosterable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("MemberStatusId")
                        .HasName("pk_member_status");

                    b.ToTable("member_status");
                });

            modelBuilder.Entity("MknMs.Domain.D5_IdentifierHistory.IdentifierHistory", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entry_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntryId"));

                    b.Property<DateOnly>("AssignedDate")
                        .HasColumnType("date")
                        .HasColumnName("assigned_date");

                    b.Property<int>("AuthorizedBy")
                        .HasColumnType("integer")
                        .HasColumnName("authorized_by");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateOnly?>("UnassignedDate")
                        .HasColumnType("date")
                        .HasColumnName("unassigned_date");

                    b.HasKey("EntryId");

                    b.HasIndex("AuthorizedBy");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_identifier_history_member");

                    b.ToTable("identifier_history");
                });

            modelBuilder.Entity("MknMs.Domain.D6_Eligibility.Eligibility", b =>
                {
                    b.Property<int>("EligibilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("eligibility_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EligibilityId"));

                    b.Property<int>("DutyId")
                        .HasColumnType("integer")
                        .HasColumnName("duty_id");

                    b.Property<int>("GrantedBy")
                        .HasColumnType("integer")
                        .HasColumnName("granted_by");

                    b.Property<DateOnly>("GrantedDate")
                        .HasColumnType("date")
                        .HasColumnName("granted_date");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<DateOnly?>("RevokedDate")
                        .HasColumnType("date")
                        .HasColumnName("revoked_date");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revoked_reason");

                    b.HasKey("EligibilityId")
                        .HasName("pk_eligibility");

                    b.HasIndex("DutyId")
                        .HasDatabaseName("ix_eligibility_duty_id");

                    b.HasIndex("GrantedBy");

                    b.HasIndex("MemberId", "DutyId")
                        .HasDatabaseName("ix_eligibility_member_duty");

                    b.ToTable("eligibility");
                });

            modelBuilder.Entity("MknMs.Domain.D7_RosterAssignment.RosterAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignmentId"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_by");

                    b.Property<string>("AssignmentSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("assignment_source");

                    b.Property<int?>("AssignmentStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_status_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DutyId")
                        .HasColumnType("integer")
                        .HasColumnName("duty_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("OccurrenceId")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_id");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("AssignmentStatusId")
                        .HasDatabaseName("ix_roster_assignment_assignment_status_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_roster_assignment_created_at");

                    b.HasIndex("DutyId")
                        .HasDatabaseName("ix_roster_assignment_duty_id");

                    b.HasIndex("OccurrenceId", "DutyId")
                        .HasDatabaseName("ix_roster_assignment_occurrence_duty");

                    b.HasIndex("MemberId", "DutyId", "OccurrenceId")
                        .IsUnique()
                        .HasDatabaseName("uq_roster_assignment_member_duty_occurrence");

                    b.ToTable("roster_assignment", t =>
                        {
                            t.HasCheckConstraint("chk_roster_assignment_source", "assignment_source IN ('Automatic', 'Manual')");
                        });
                });

            modelBuilder.Entity("MknMs.Domain.D8_AttendanceRecord.AttendanceRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecordId"));

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("OccurrenceId")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("RecordId");

                    b.HasIndex("OccurrenceId")
                        .HasDatabaseName("ix_attendance_record_occurrence");

                    b.HasIndex("MemberId", "OccurrenceId")
                        .IsUnique()
                        .HasDatabaseName("uq_attendance_record_member_occurrence");

                    b.HasIndex("MemberId", "Timestamp")
                        .HasDatabaseName("ix_attendance_record_member_ts");

                    b.ToTable("attendance_record");
                });

            modelBuilder.Entity("MknMs.Domain.D9_EventProgram.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("EventId")
                        .HasName("pk_event");

                    b.ToTable("event");
                });

            modelBuilder.Entity("MknMs.Domain.D9_EventProgram.EventBranch", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.HasKey("EventId", "BranchId");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_event_branch_branch_id");

                    b.ToTable("event_branch");
                });

            modelBuilder.Entity("MknMs.Domain.D9_EventProgram.EventDuty", b =>
                {
                    b.Property<int>("EventDutyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("event_duty_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventDutyId"));

                    b.Property<int>("AssignedMemberId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_member_id");

                    b.Property<int?>("AssignmentStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_status_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("ProgramItemId")
                        .HasColumnType("integer")
                        .HasColumnName("program_item_id");

                    b.HasKey("EventDutyId")
                        .HasName("pk_event_duty");

                    b.HasIndex("AssignedMemberId")
                        .HasDatabaseName("ix_event_duty_assigned_member");

                    b.HasIndex("AssignmentStatusId")
                        .HasDatabaseName("ix_event_duty_assignment_status_id");

                    b.HasIndex("ProgramItemId")
                        .HasDatabaseName("ix_event_duty_program_item");

                    b.ToTable("event_duty");
                });

            modelBuilder.Entity("MknMs.Domain.D9_EventProgram.Program", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("program_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgramId"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("ProgramId")
                        .HasName("pk_program");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("uq_program_event");

                    b.ToTable("program");
                });

            modelBuilder.Entity("MknMs.Domain.D9_EventProgram.ProgramItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int>("ProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("program_id");

                    b.Property<DateTimeOffset>("ScheduledEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_end");

                    b.Property<DateTimeOffset>("ScheduledStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.Property<int?>("ServiceDefId")
                        .HasColumnType("integer")
                        .HasColumnName("service_def_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("ItemId");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("ix_program_item_program");

                    b.HasIndex("ServiceDefId")
                        .HasDatabaseName("ix_program_item_service_def");

                    b.ToTable("program_item");
                });

            modelBuilder.Entity("MknMs.Domain.D12_MaterializerRun.MaterializerRun", b =>
                {
                    b.HasOne("MknMs.Domain.D4_Member.Admin", "TriggeredByAdmin")
                        .WithMany()
                        .HasForeignKey("TriggeredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_materializer_run_admins_triggered_by_admin_admin_id");

                    b.Navigation("TriggeredByAdmin");
                });

            modelBuilder.Entity("MknMs.Domain.D13_AttendanceRule.AttendanceRule", b =>
                {
                    b.HasOne("MknMs.Domain.D4_Member.MemberStatus", "OutcomeStatus")
                        .WithMany()
                        .HasForeignKey("OutcomeStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attendance_rule_member_statuses_outcome_status_id");

                    b.Navigation("OutcomeStatus");
                });

            modelBuilder.Entity("MknMs.Domain.D13_AttendanceRule.AttendanceRuleScope", b =>
                {
                    b.HasOne("MknMs.Domain.D13_AttendanceRule.AttendanceRule", "AttendanceRule")
                        .WithMany()
                        .HasForeignKey("AttendanceRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_rule_scope_attendance_rule_attendance_rule_id");

                    b.Navigation("AttendanceRule");
                });

            modelBuilder.Entity("MknMs.Domain.D13_AttendanceRule.Readmission", b =>
                {
                    b.HasOne("MknMs.Domain.D4_Member.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_readmission_members_member_id");

                    b.HasOne("MknMs.Domain.D4_Member.Admin", "PerformedByAdmin")
                        .WithMany()
                        .HasForeignKey("PerformedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_readmission_admins_performed_by_admin_id");

                    b.Navigation("Member");

                    b.Navigation("PerformedByAdmin");
                });

            modelBuilder.Entity("MknMs.Domain.D14_ConfigurationAudit.ConfigurationAuditLog", b =>
                {
                    b.HasOne("MknMs.Domain.D4_Member.Admin", "ApprovedByAdmin")
                        .WithMany()
                        .HasForeignKey("ApprovedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_configuration_audit_log_admins_approved_by_admin_id");

                    b.HasOne("MknMs.Domain.D4_Member.Admin", "InitiatedByAdmin")
                        .WithMany()
                        .HasForeignKey("InitiatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_configuration_audit_log_admins_initiated_by_admin_id");

                    b.Navigation("ApprovedByAdmin");

                    b.Navigation("InitiatedByAdmin");
                });

            modelBuilder.Entity("MknMs.Domain.D14_ConfigurationAudit.EntityDeletionPolicy", b =>
                {
                    b.HasOne("MknMs.Domain.D10_ConfigLookups.PermissionTier", "RequiredDeactivatePermissionTier")
                        .WithMany()
                        .HasForeignKey("RequiredDeactivatePermissionTierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_entity_deletion_policy_permission_tier_required_deactivate_~");

                    b.HasOne("MknMs.Domain.D10_ConfigLookups.PermissionTier", "RequiredDeletePermissionTier")
                        .WithMany()
                        .HasForeignKey("RequiredDeletePermissionTierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_entity_deletion_policy_permission_tier_required_delete_perm~");

                    b.Navigation("RequiredDeactivatePermissionTier");

                    b.Navigation("RequiredDeletePermissionTier");
                });

            modelBuilder.Entity("MknMs.Domain.D14_ConfigurationAudit.NotificationSubscription", b =>
                {
                    b.HasOne("MknMs.Domain.D4_Member.Admin", "RecipientAdmin")
                        .WithMany()
                        .HasForeignKey("RecipientAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notification_subscription_admins_recipient_admin_id");

                    b.HasOne("MknMs.Domain.D10_ConfigLookups.PermissionTier", "RecipientTier")
                        .WithMany()
                        .HasForeignKey("RecipientTierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notification_subscription_permission_tier_recipient_tier_id");

                    b.Navigation("RecipientAdmin");

                    b.Navigation("RecipientTier");
                });

            modelBuilder.Entity("MknMs.Domain.D2_DutyRule.DutyRule", b =>
                {
                    b.HasOne("MknMs.Domain.D1_RoleDuty.Duty", "Duty")
                        .WithMany()
                        .HasForeignKey("DutyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_duty_rule_duty_duty_id");

                    b.Navigation("Duty");
                });

            modelBuilder.Entity("MknMs.Domain.D3_BranchTimeSlotService.BranchTimeSlot", b =>
                {
                    b.HasOne("MknMs.Domain.D3_BranchTimeSlotService.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branch_time_slot_branch_branch_id");

                    b.HasOne("MknMs.Domain.D10_ConfigLookups.TimeOfDay", "TimeOfDay")
                        .WithMany()
                        .HasForeignKey("TimeOfDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branch_time_slot_time_of_day_time_of_day_id");

                    b.Navigation("Branch");

                    b.Navigation("TimeOfDay");
                });

            modelBuilder.Entity("MknMs.Domain.D3_BranchTimeSlotService.ServiceDefinition", b =>
                {
                    b.HasOne("MknMs.Domain.D3_BranchTimeSlotService.Branch", "OwningBranch")
                        .WithMany()
                        .HasForeignKey("OwningBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_definition_branch_owning_branch_id");

                    b.HasOne("MknMs.Domain.D10_ConfigLookups.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_definition_service_type_service_type_id");

                    b.Navigation("OwningBranch");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("MknMs.Domain.D3_BranchTimeSlotService.ServiceDefinitionDuty", b =>
                {
                    b.HasOne("MknMs.Domain.D1_RoleDuty.Duty", "Duty")
                        .WithMany()
                        .HasForeignKey("DutyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_definition_duty_duty_duty_id");

                    b.HasOne("MknMs.Domain.D3_BranchTimeSlotService.ServiceDefinition", "ServiceDefinition")
                        .WithMany()
                        .HasForeignKey("ServiceDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_definition_duty_service_definition_service_definiti~");

                    b.Navigation("Duty");

                    b.Navigation("ServiceDefinition");
                });

            modelBuilder.Entity("MknMs.Domain.D3_BranchTimeSlotService.ServiceOccurrence", b =>
                {
                    b.HasOne("MknMs.Domain.D4_Member.Admin", "ChangedByAdmin")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_occurrence_admins_changed_by_admin_admin_id");

                    b.HasOne("MknMs.Domain.D4_Member.Admin", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_occurrence_admins_created_by_admin_admin_id");

                    b.HasOne("MknMs.Domain.D9_EventProgram.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_occurrence_events_event_id");

                    b.HasOne("MknMs.Domain.D10_ConfigLookups.OutcomeState", "FillStatus")
                        .WithMany()
                        .HasForeignKey("FillStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_occurrence_outcome_state_fill_status_id");

                    b.HasOne("MknMs.Domain.D3_BranchTimeSlotService.ServiceSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_occurrence_service_schedules_schedule_id");

                    b.HasOne("MknMs.Domain.D10_ConfigLookups.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_occurrence_service_type_service_type_id");

                    b.Navigation("ChangedByAdmin");

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("Event");

                    b.Navigation("FillStatus");

                    b.Navigation("Schedule");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("MknMs.Domain.D3_BranchTimeSlotService.ServiceOccurrenceDuty", b =>
                {
                    b.HasOne("MknMs.Domain.D1_RoleDuty.Duty", "Duty")
                        .WithMany()
                        .HasForeignKey("DutyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_occurrence_duty_duty_duty_id");

                    b.HasOne("MknMs.Domain.D3_BranchTimeSlotService.ServiceOccurrence", "ServiceOccurrence")
                        .WithMany()
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_occurrence_duty_service_occurrence_service_occurren~");

                    b.Navigation("Duty");

                    b.Navigation("ServiceOccurrence");
                });

            modelBuilder.Entity("MknMs.Domain.D3_BranchTimeSlotService.ServiceSchedule", b =>
                {
                    b.HasOne("MknMs.Domain.D3_BranchTimeSlotService.ServiceDefinition", "ServiceDefinition")
                        .WithMany()
                        .HasForeignKey("ServiceDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_schedule_service_definition_service_definition_temp~");

                    b.HasOne("MknMs.Domain.D3_BranchTimeSlotService.BranchTimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_schedule_branch_time_slot_time_slot_id");

                    b.Navigation("ServiceDefinition");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("MknMs.Domain.D4_Member.Admin", b =>
                {
                    b.HasOne("MknMs.Domain.D4_Member.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admin_members_member_id");

                    b.HasOne("MknMs.Domain.D10_ConfigLookups.PermissionTier", "PermissionTier")
                        .WithMany()
                        .HasForeignKey("PermissionTierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admin_permission_tier_permission_tier_id");

                    b.Navigation("Member");

                    b.Navigation("PermissionTier");
                });

            modelBuilder.Entity("MknMs.Domain.D4_Member.Member", b =>
                {
                    b.HasOne("MknMs.Domain.D3_BranchTimeSlotService.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_member_branch_branch_id");

                    b.HasOne("MknMs.Domain.D1_RoleDuty.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_member_role_role_id");

                    b.Navigation("Branch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MknMs.Domain.D4_Member.MemberAttributeValue", b =>
                {
                    b.HasOne("MknMs.Domain.D4_Member.AttributeType", "AttributeType")
                        .WithMany()
                        .HasForeignKey("AttributeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_member_attribute_value_attribute_type_attribute_type_id");

                    b.HasOne("MknMs.Domain.D4_Member.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_member_attribute_value_member_member_id");

                    b.HasOne("MknMs.Domain.D4_Member.Admin", "RecordedByAdmin")
                        .WithMany()
                        .HasForeignKey("RecordedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_member_attribute_value_admin_recorded_by_admin_admin_id");

                    b.Navigation("AttributeType");

                    b.Navigation("Member");

                    b.Navigation("RecordedByAdmin");
                });

            modelBuilder.Entity("MknMs.Domain.D5_IdentifierHistory.IdentifierHistory", b =>
                {
                    b.HasOne("MknMs.Domain.D4_Member.Admin", "AuthorizedByAdmin")
                        .WithMany()
                        .HasForeignKey("AuthorizedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_identifier_history_admin_authorized_by_admin_admin_id");

                    b.HasOne("MknMs.Domain.D4_Member.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_identifier_history_member_member_id");

                    b.Navigation("AuthorizedByAdmin");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MknMs.Domain.D6_Eligibility.Eligibility", b =>
                {
                    b.HasOne("MknMs.Domain.D1_RoleDuty.Duty", "Duty")
                        .WithMany()
                        .HasForeignKey("DutyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eligibility_duty_duty_id");

                    b.HasOne("MknMs.Domain.D4_Member.Admin", "GrantedByAdmin")
                        .WithMany()
                        .HasForeignKey("GrantedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eligibility_admin_granted_by_admin_admin_id");

                    b.HasOne("MknMs.Domain.D4_Member.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eligibility_member_member_id");

                    b.Navigation("Duty");

                    b.Navigation("GrantedByAdmin");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MknMs.Domain.D7_RosterAssignment.RosterAssignment", b =>
                {
                    b.HasOne("MknMs.Domain.D4_Member.Admin", "ApprovedByAdmin")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roster_assignment_admin_approved_by_admin_admin_id");

                    b.HasOne("MknMs.Domain.D4_Member.Admin", "AssignedByAdmin")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roster_assignment_admin_assigned_by_admin_admin_id");

                    b.HasOne("MknMs.Domain.D10_ConfigLookups.AssignmentStatus", "AssignmentStatus")
                        .WithMany()
                        .HasForeignKey("AssignmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roster_assignment_assignment_status_assignment_status_id");

                    b.HasOne("MknMs.Domain.D1_RoleDuty.Duty", "Duty")
                        .WithMany()
                        .HasForeignKey("DutyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roster_assignment_duty_duty_id");

                    b.HasOne("MknMs.Domain.D4_Member.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roster_assignment_member_member_id");

                    b.HasOne("MknMs.Domain.D3_BranchTimeSlotService.ServiceOccurrence", "ServiceOccurrence")
                        .WithMany()
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roster_assignment_service_occurrence_service_occurrence_tem~");

                    b.Navigation("ApprovedByAdmin");

                    b.Navigation("AssignedByAdmin");

                    b.Navigation("AssignmentStatus");

                    b.Navigation("Duty");

                    b.Navigation("Member");

                    b.Navigation("ServiceOccurrence");
                });

            modelBuilder.Entity("MknMs.Domain.D8_AttendanceRecord.AttendanceRecord", b =>
                {
                    b.HasOne("MknMs.Domain.D4_Member.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_record_member_member_id");

                    b.HasOne("MknMs.Domain.D3_BranchTimeSlotService.ServiceOccurrence", "ServiceOccurrence")
                        .WithMany()
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_record_service_occurrence_service_occurrence_tem~");

                    b.Navigation("Member");

                    b.Navigation("ServiceOccurrence");
                });

            modelBuilder.Entity("MknMs.Domain.D9_EventProgram.EventBranch", b =>
                {
                    b.HasOne("MknMs.Domain.D3_BranchTimeSlotService.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_branch_branch_branch_id");

                    b.HasOne("MknMs.Domain.D9_EventProgram.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_branch_event_event_id");

                    b.Navigation("Branch");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MknMs.Domain.D9_EventProgram.EventDuty", b =>
                {
                    b.HasOne("MknMs.Domain.D4_Member.Member", "AssignedMember")
                        .WithMany()
                        .HasForeignKey("AssignedMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_duty_member_assigned_member_id");

                    b.HasOne("MknMs.Domain.D10_ConfigLookups.AssignmentStatus", "AssignmentStatus")
                        .WithMany()
                        .HasForeignKey("AssignmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_event_duty_assignment_status_assignment_status_id");

                    b.HasOne("MknMs.Domain.D9_EventProgram.ProgramItem", "ProgramItem")
                        .WithMany()
                        .HasForeignKey("ProgramItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_duty_program_items_program_item_id");

                    b.Navigation("AssignedMember");

                    b.Navigation("AssignmentStatus");

                    b.Navigation("ProgramItem");
                });

            modelBuilder.Entity("MknMs.Domain.D9_EventProgram.Program", b =>
                {
                    b.HasOne("MknMs.Domain.D9_EventProgram.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_program_event_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MknMs.Domain.D9_EventProgram.ProgramItem", b =>
                {
                    b.HasOne("MknMs.Domain.D9_EventProgram.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_program_item_program_program_id");

                    b.HasOne("MknMs.Domain.D3_BranchTimeSlotService.ServiceDefinition", "ServiceDefinition")
                        .WithMany()
                        .HasForeignKey("ServiceDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_program_item_service_definition_service_definition_temp_id");

                    b.Navigation("Program");

                    b.Navigation("ServiceDefinition");
                });
#pragma warning restore 612, 618
        }
    }
}
