<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MknMs.Domain\MknMs.Domain.csproj" />
    <ProjectReference Include="..\MknMs.Persistence\MknMs.Persistence.csproj" />
    <ProjectReference Include="..\MknMs.Application\MknMs.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
